ELLIE_USERNAME = 1219843066

DOWNLOAD_FLAG = "| All"

PATH_TO_LOCAL_LIBRARY = "/Users/ellie/Music/Tracks"
PATH_TO_DOWNLOAD_LOGS = "/Users/ellie/Music/Download_Logs"

TRACKS_TO_DOWNLOAD_PLAYLIST_ID = "3NBGj2ql62julm947YxrZq"